version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
        environment:
          JOBS: 1
    steps:
      - checkout
      - run: sudo npm install -g yarn@0
      - run: sudo yarn global add greenkeeper-lockfile@1
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - deps-
      - run: yarn
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: 'node_modules'
      - run: yarn ci:before
      - run: yarn test:ci
      - run: yarn build
      - run: yarn ci:after
      - run: lerna-semantic-release pre && lerna-semantic-release perform
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_artifacts:
          path: dist
          prefix: dist
      - store_test_results:
          path: test-report.xml
