version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    branches:
      only:
        - master
        - v0.2.x
    steps:
      - checkout
      - run:
          name: Update yarn
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - deps-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: 'node_modules'
      - run:
          name: Rollup build
          command: yarn build
      - run:
          name: Test & coverage
          command: yarn test.ci
      - store_artifacts:
          path: test-report.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_artifacts:
          path: dist
          prefix: dist
      - store_test_results:
          path: test-report.xml
      - run: bash <(curl -s https://codecov.io/bash)
