version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        environment:
          JOBS: 1
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: git config --global user.email ${GH_USER_EMAIL}
      - run: git config --global user.name ${GH_USER_NAME}
      - run: sudo yarn global add greenkeeper-lockfile@1
      - run: sudo yarn global add lerna@3
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - deps-
      - run: yarn
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: 'node_modules'
      - run: yarn ci:before
      - run: yarn test:ci
      - run: if [ ${CIRCLE_BRANCH} == "master" ]; then lerna version --create-release github --yes; fi
      - run: yarn build
      - run: yarn ci:after
      - run: if [ ${CIRCLE_BRANCH} == "master" ]; then lerna publish from-package --yes; fi
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_artifacts:
          path: dist
          prefix: dist
      - store_test_results:
          path: test-report.xml
